from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

STARBUCKS_DRINK_CATEGORY_CODES = (
    "W0000171",
    "W0000060",
    "W0000003",
    "W0000004",
    "W0000005",
    "W0000422",
    "W0000061",
    "W0000075",
    "W0000053",
    "W0000062",
)
STARBUCKS_FOOD_CATEGORY_CODES = (
    "W0000013",
    "W0000032",
    "W0000033",
    "W0000054",
    "W0000055",
    "W0000056",
    "W0000064",
    "W0000554",
    "W0000126",
    "W0000074",
    "W0000347",
)


@dataclass(slots=True)
class NewProductSourceDefinition:
    source_key: str
    title: str
    brand: str
    source_type: str
    channel: str
    site_url: str
    crawl_url: str
    parser_type: str
    parser_config: dict[str, Any] = field(default_factory=dict)
    source_origin: str = "code"
    discovery_metadata: dict[str, Any] = field(default_factory=dict)


def build_source_taxonomy(
    sector_key: str,
    *,
    display_brand: str | None = None,
) -> dict[str, Any]:
    metadata: dict[str, Any] = {"sector_key": sector_key}
    if display_brand:
        metadata["display_brand"] = display_brand
    return metadata


# 신규 브랜드는 가능하면 이 파일에만 추가해서 관리한다.
# parser_type은 new_products.py의 핸들러와 매핑되고,
# 같은 템플릿이면 parser_config만 바꿔서 등록하면 된다.
SOURCE_DEFINITIONS: tuple[NewProductSourceDefinition, ...] = (
    NewProductSourceDefinition(
        source_key="emart24_fresh_food",
        title="이마트24 Fresh Food",
        brand="이마트24",
        source_type="convenience",
        channel="Fresh Food",
        site_url="https://www.emart24.co.kr/goods/ff",
        crawl_url="https://www.emart24.co.kr/goods/ff",
        parser_type="emart24_fresh_food",
        parser_config={
            "max_pages": 3,
        },
    ),
    NewProductSourceDefinition(
        source_key="lotteeatz_launch_events",
        title="LOTTE EATZ 신제품 이벤트",
        brand="LOTTE EATZ",
        source_type="franchise",
        channel="이벤트",
        site_url="https://www.lotteeatz.com/event/main",
        crawl_url="https://www.lotteeatz.com/event/main",
        parser_type="lotteeatz_launch_events",
        parser_config={
            "max_items": 40,
        },
        discovery_metadata=build_source_taxonomy(
            "other",
            display_brand="롯데잇츠",
        ),
    ),
    NewProductSourceDefinition(
        source_key="paikdabang_news",
        title="빽다방 신메뉴 소식",
        brand="빽다방",
        source_type="franchise",
        channel="소식",
        site_url="https://paikdabang.com/news/",
        crawl_url="https://paikdabang.com/news/",
        parser_type="html_board_news_table",
        parser_config={
            "row_selector": ".board_wrap table tbody tr",
            "min_cell_count": 4,
            "category_cell_index": 1,
            "title_cell_index": 2,
            "date_cell_index": 3,
            "date_format": "dash",
            "detail_link_selector": "a[href]",
            "required_category": "소식",
            "default_category": "신메뉴 소식",
            "summary_fallback": "{brand} 공식 소식",
            "detail_image_markers": ("/wp-content/uploads/",),
            "max_items": 40,
        },
        discovery_metadata=build_source_taxonomy("cafe"),
    ),
    NewProductSourceDefinition(
        source_key="kfc_new_menu",
        title="KFC 신메뉴",
        brand="KFC",
        source_type="franchise",
        channel="신메뉴",
        site_url="https://www.kfckorea.com/promotion/newMenu",
        crawl_url="https://www.kfckorea.com/promotion/newMenu",
        parser_type="kfc_new_menu",
        parser_config={
            "max_items": 20,
        },
        discovery_metadata=build_source_taxonomy("burger"),
    ),
    NewProductSourceDefinition(
        source_key="momstouch_new_menu",
        title="맘스터치 New 메뉴",
        brand="맘스터치",
        source_type="franchise",
        channel="메뉴",
        site_url="https://www.momstouch.co.kr/menu/new.php?s_sect1=new",
        crawl_url="https://www.momstouch.co.kr/menu/new.php?s_sect1=new",
        parser_type="html_paged_new_menu",
        parser_config={
            "max_pages": 3,
            "item_selector": '.menu-list li a[href*="go_view"]',
            "id_pattern": r"go_view\('?(?P<id>\d+)'?\)",
            "category_selector": ".sub-text",
            "title_selector": "h3",
            "english_name_selector": "h3 span",
            "image_style_selector": "figure span",
            "detail_url_template": "https://www.momstouch.co.kr/menu/view.php?idx={external_id}",
            "default_category": "신제품 메뉴",
            "summary_fallback": "{brand} 공식 신제품 메뉴",
            "published_at_source": "asset_upload_unix",
            "image_timestamp_pattern": r"/(\d{10})-[A-Z0-9]+\.",
        },
        discovery_metadata=build_source_taxonomy("burger"),
    ),
    NewProductSourceDefinition(
        source_key="dominos_new_menu",
        title="도미노피자 NEW 메뉴",
        brand="도미노피자",
        source_type="franchise",
        channel="메뉴",
        site_url="https://web.dominos.co.kr/goods/list?dsp_ctgr=C0101",
        crawl_url="https://web.dominos.co.kr/goods/list?dsp_ctgr=C0101",
        parser_type="html_badge_menu",
        parser_config={
            "scan_limit": 80,
            "item_selector": "div.menu-list ul li",
            "badge_selector": ".label.sale",
            "badge_text": "NEW",
            "detail_link_selector": ".prd-img a[href]",
            "detail_href_strategy": "dominos",
            "external_id_pattern": r"code_01=([A-Z0-9]+)",
            "title_selector": ".subject",
            "hashtag_selector": ".hashtag span",
            "image_selector": "img",
            "image_attr_order": ("data-src", "src"),
            "default_category": "피자",
            "category_heading_tags": ("h3", "h4"),
            "category_exclude_keywords": ("치킨&사이드", "먹어유"),
            "category_max_length": 18,
            "summary_fallback": "{brand} 공식 NEW 메뉴",
            "summary_hashtag_limit": 2,
            "published_at_source": "asset_upload_ymd",
            "image_timestamp_pattern": r"/(\d{8})_[A-Za-z0-9]+\.",
        },
        discovery_metadata=build_source_taxonomy("pizza"),
    ),
    NewProductSourceDefinition(
        source_key="mcdonalds_promotion",
        title="맥도날드 프로모션",
        brand="맥도날드",
        source_type="franchise",
        channel="프로모션",
        site_url="https://www.mcdonalds.co.kr/kor/promotion/list",
        crawl_url="https://www.mcdonalds.co.kr/kor/promotion/list",
        parser_type="mcdonalds_promotion",
        parser_config={
            "max_items": 20,
        },
        discovery_metadata=build_source_taxonomy("burger"),
    ),
    NewProductSourceDefinition(
        source_key="burgerking_event_feed",
        title="버거킹 신상 이벤트",
        brand="버거킹",
        source_type="franchise",
        channel="이벤트",
        site_url="https://www.burgerking.co.kr",
        crawl_url="https://www.burgerking.co.kr/event/ongoing",
        parser_type="json_event_feed",
        parser_config={
            "endpoint_url": "https://www.burgerking.co.kr/burgerking/BKR0608.json",
            "http_method": "POST",
            "message_payload": {
                "header": {
                    "result": True,
                    "error_code": "",
                    "error_text": "",
                    "info_text": "",
                    "message_version": "",
                    "login_session_id": "",
                    "trcode": "BKR0608",
                    "cd_call_chnn": "01",
                },
                "body": {
                    "cdTypeEvent": "00",
                    "page": "1",
                    "pageCount": "20",
                    "tpStatusEvent": "C",
                },
            },
            "list_path": "body.eventList",
            "id_field": "eventId",
            "title_field": "eventTitle",
            "image_field": "imageUrlWeb",
            "fallback_image_field": "imageUrlApp",
            "start_date_field": "dtStart",
            "end_date_field": "dtEnd",
            "start_date_format": "compact",
            "end_date_format": "compact",
            "detail_url_template": "https://www.burgerking.co.kr/event/detail/{external_id}",
            "default_category": "신상 이벤트",
            "summary_fallback": "{brand} 공식 신상 이벤트",
            "allow_food_names_without_keyword": True,
            "short_name_max_length": 28,
            "name_hint_keywords": (
                "와퍼",
                "버거",
                "비프",
                "치즈",
                "불고기",
                "베이컨",
                "치킨",
                "아포가토",
                "어니언링",
                "킹퓨전",
                "오믈렛",
                "크리스퍼",
                "킹모닝",
            ),
            "title_block_keywords": (
                "할인",
                "적립",
                "쿠폰",
                "알림",
                "딜리버리",
                "올데이킹",
                "GRAND OPEN",
                "공유",
                "도전하라",
                "하루종일",
            ),
            "max_items": 40,
        },
        discovery_metadata=build_source_taxonomy("burger"),
    ),
    NewProductSourceDefinition(
        source_key="subway_event",
        title="서브웨이 이벤트",
        brand="서브웨이",
        source_type="franchise",
        channel="이벤트",
        site_url="https://www.subway.co.kr",
        crawl_url="https://www.subway.co.kr/eventList",
        parser_type="html_event_card_list",
        parser_config={
            "item_selector": ".event_list_wrapper li",
            "title_selector": ".title",
            "date_selector": ".date em",
            "date_format": "dot",
            "image_selector": ".event_img img",
            "onclick_pattern": r"view\.view\((?P<id>\d+)\)",
            "detail_url_template": "https://www.subway.co.kr/eventView?eventIdx={external_id}",
            "default_category": "이벤트",
            "summary_fallback": "{brand} 공식 이벤트",
            "max_items": 40,
            "allow_food_names_without_keyword": True,
            "short_name_max_length": 18,
        },
        discovery_metadata=build_source_taxonomy("sandwich"),
    ),
    NewProductSourceDefinition(
        source_key="composecoffee_event",
        title="컴포즈커피 이벤트",
        brand="컴포즈커피",
        source_type="franchise",
        channel="이벤트",
        site_url="https://composecoffee.com",
        crawl_url="https://composecoffee.com/event",
        parser_type="html_card_news_grid",
        parser_config={
            "item_selector": ".board_list li",
            "detail_link_selector": "a.doc_link[href]",
            "title_selector": ".doc_title",
            "date_selector": ".regdate",
            "date_format": "dash_datetime",
            "image_selector": ".image_area img",
            "default_category": "신메뉴 이벤트",
            "summary_fallback": "{brand} 공식 이벤트",
            "max_items": 40,
        },
        discovery_metadata=build_source_taxonomy("cafe"),
    ),
    NewProductSourceDefinition(
        source_key="gongcha_event_list",
        title="공차 이벤트",
        brand="공차",
        source_type="franchise",
        channel="이벤트",
        site_url="https://www.gong-cha.co.kr/brand",
        crawl_url="https://www.gong-cha.co.kr/brand/content/eventlist",
        parser_type="html_media_event_list",
        parser_config={
            "item_selector": ".event ul > li",
            "detail_link_selector": ".figure a[href], .event-text a[href], a[href]",
            "title_selector": ".event-text .t1",
            "date_selector": ".event-text .t2",
            "image_selector": ".figure img",
            "date_format": "dot",
            "default_category": "이벤트",
            "summary_fallback": "{brand} 공식 이벤트",
            "max_items": 40,
        },
        discovery_metadata=build_source_taxonomy("cafe"),
    ),
    NewProductSourceDefinition(
        source_key="puradak_event_list",
        title="푸라닭 이벤트",
        brand="푸라닭",
        source_type="franchise",
        channel="이벤트",
        site_url="https://www.puradakchicken.com/news/event.asp",
        crawl_url="https://www.puradakchicken.com/news/event.asp",
        parser_type="html_media_event_list",
        parser_config={
            "item_selector": ".photo_list .list li",
            "detail_link_selector": "a[href]",
            "title_selector": ".title",
            "date_selector": ".txt",
            "image_selector": ".thumb img",
            "date_format": "dash",
            "default_category": "이벤트",
            "summary_fallback": "{brand} 공식 이벤트",
            "max_items": 40,
            "allow_food_names_without_keyword": True,
            "name_hint_keywords": (
                "치킨",
                "윙",
                "닭",
                "패키지",
                "마불로",
                "악마",
            ),
            "title_block_keywords": (
                "할인",
                "전메뉴",
                "쿠폰",
                "앱",
                "회원",
                "오픈",
                "후원",
                "채용",
                "리뷰",
                "호평",
            ),
        },
    ),
    NewProductSourceDefinition(
        source_key="starbucks_menu",
        title="스타벅스 신규 메뉴",
        brand="스타벅스",
        source_type="franchise",
        channel="메뉴",
        site_url="https://www.starbucks.co.kr/menu/drink_list.do",
        crawl_url="https://www.starbucks.co.kr/menu/drink_list.do",
        parser_type="json_menu_feed",
        parser_config={
            "category_codes": STARBUCKS_DRINK_CATEGORY_CODES + STARBUCKS_FOOD_CATEGORY_CODES,
            "food_category_codes": STARBUCKS_FOOD_CATEGORY_CODES,
            "endpoint_template": "https://www.starbucks.co.kr/upload/json/menu/{category_code}.js",
            "request_form": {
                "CATE_CD": "{category_code}",
                "SOLD_OUT": "1",
            },
            "response_list_key": "list",
            "id_field": "product_CD",
            "name_field": "product_NM",
            "category_field": "cate_NAME",
            "fallback_category_field": "sell_CAT",
            "summary_field": "content",
            "image_field": "file_PATH",
            "new_flag_field": "newicon",
            "new_flag_value": "Y",
            "start_date_field": "new_SDATE",
            "end_date_field": "new_EDATE",
            "food_listing_url": "https://www.starbucks.co.kr/menu/food_list.do",
            "fallback_category": "신규 메뉴",
            "summary_fallback": "{category} · {brand} 신규 메뉴",
            "start_date_format": "compact",
            "end_date_format": "compact",
            "published_at_source": "explicit",
        },
        discovery_metadata=build_source_taxonomy("cafe"),
    ),
    NewProductSourceDefinition(
        source_key="mega_seasonal_menu",
        title="메가MGC 시즌 신메뉴",
        brand="메가MGC커피",
        source_type="franchise",
        channel="메인",
        site_url="https://www.mega-mgccoffee.com/",
        crawl_url="https://www.mega-mgccoffee.com/",
        parser_type="mega_seasonal_menu",
        parser_config={
            "max_items": 12,
        },
        discovery_metadata=build_source_taxonomy("cafe"),
    ),
)
